site_name: "Alisp: Lisp intrpeter written in C++"
site_author: "Stanislav Arnaudov"
site_favicon: favicon.ico
repo_url: https://github.com/palikar/alisp
edit_uri: edit/master/doc/
copyright: "Copyright (C) 2019-2020 Stanislav Arnaudoc"
docs_dir: doc
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      separator: "_"
      permalink: "#"
extra_css:
  - css/extra.css
  - css/style.css
nav:
- Home: index.md
- Language Reference: reference.md
- Basic Documentation: basic_doc.md
- File Manipulation: files_doc.md
- Streams Manipulation: streams_doc.md
- Modules:
    - Index: './modules/index.md'
    - Fileio : './modules/fileio.md'
    - Math : './modules/math.md'
    - Memory : './modules/memory.md'
    - Platform : './modules/platform.md'
    - System : './modules/system.md'
    - Time : './modules/time.md'
    - Dash : './modules/dash.md'
    - S : './modules/s.md'
    - Base64 : './modules/base64.md'
    - Fmt : './modules/fmt.md'
    - Func : './modules/func.md'
    - Json : './modules/json.md'
    - XML : './modules/xml.md'
    - Locale : './modules/locale.md'
    - Process : './modules/process.md'
    - Random : './modules/random.md'
    - Re : './modules/re.md'

theme: readthedocs
