site_name: "Alisp: Lisp intrpeter written in C++"
site_author: "Stanislav Arnaudov"
repo_url: https://github.com/palikar/alisp
edit_uri: edit/master/doc/
copyright: "Copyright (C) 2019-2020 Stanislav Arnaudoc"
docs_dir: doc
nav:
- Home: index.md
- Language Reference: reference.md
- Basic Documentation: basic_doc.md
- File Manipulation: files_doc.md
- Streams Manipulation: streams_doc.md
markdown_extensions:
  - admonition
  - mkautodoc
extra_css:
  - css/extra.css
theme: readthedocs
plugins:
    - search
    
